### PR TITLE
Added virtual-host with proper configuration for rewrite rules

### PR DESCRIPTION
**Pull request by rawkode**

### CODE REVIEW

**Comment by rawkode** [comment]
Not sure if you'd rather the virtual-host configuration was inside app/config/*, or perhaps even  in some sort of ops directory in the root.

Open to thoughts here, @dragoonis and @noisebleed ?

**Comment by rawkode** [comment]
Ping @dragoonis @noisebleed

**Comment by BenExile** [comment]
Now working for me after running `vagrant up && vagrant ssh -c "docker logs -f ppi"`. Tested by navigating to the /404 route which previously wasn't working due to mod_rewrite not being enabled.

I don't think the VirtualHost configuration will change on a per environment basis? Maybe consider putting it in app/ops/virtualhost.conf?

**Comment by rawkode** [comment]
@BenExile The log level is likely to change depending on environment, though we could configure that through an environment variable, ${APACHE_LOG_LEVEL}?

**Comment by noisebleed** [comment]
@rawkode the log level is automatically controlled by the environment: `dev` vs `prod`.

**Comment by rawkode** [comment]
@noisebleed The Apache2 log level?

**Comment by noisebleed** [comment]
@rawkode no, `PPI\App` log level, available at constructor time. But the level you pass to `PPI\App` may come from the webserver. That's down to the user.

**Comment by rawkode** [comment]
Exactly, @noisebleed - I believe you've misunderstood the discussion regarding logging.

**Pull request merged**
